AllCops:
  # Include gemspec and Rakefile
  Include:
    - '*.gemspec'
    - Rakefile
    - config.ru
    - db/migrate/**/*
  Exclude:
    - bin/**
    - db/migrate/**
    - spec/dummy/**/*
    - spec/internal/**/*

  # By default, the rails cops are not run. Override in project or home
  # directory .rubocop.yml files, or by giving the -R/--rails option.
  RunRailsCops: true

AlignHash:
  Exclude:
    - 'config/initializers/simple_form.rb'
RegexpLiteral:
  Exclude:
    - '*.gemspec'

SingleSpaceBeforeFirstArg:
  Enabled: false

Style/Documentation:
  Enabled: false

LineLength:
  # Max: 120
  Enabled: false

MethodLength:
  Enabled: false
