AllCops:
  # Include gemspec and Rakefile
  Include:
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/config.ru'
    - 'db/migrate/**/*'
  Exclude:
    - 'bin/**/*'
    - 'spec/i18n_spec.rb'
    - 'spec/dummy/**/*'
    - 'spec/internal/**/*'
    - 'vendor/**/*'

  # By default, the rails cops are not run. Override in project or home
  # directory .rubocop.yml files, or by giving the -R/--rails option.
  RunRailsCops: true

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

Style/AlignHash:
  Exclude:
    - 'config/initializers/simple_form.rb'

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - '*.gemspec'

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/SpaceAroundOperators:
  MultiSpaceAllowedForOperators:
    - '='
    - '=>'
    - '||='

Metrics/LineLength:
  # Max: 120
  Enabled: false

Metrics/MethodLength:
  Enabled: false
