language: ruby
sudo: false
before_install: gem install bundler
before_script:
  - bundle update
  - bundle exec rake dummy:app --trace
  - bundle exec rake app:db:migrate --trace
  - bundle exec rake app:db:test:prepare --trace
cache: bundler
script: bundle exec rspec
env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite
rvm:
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.2.4
  - 2.3.0
matrix:
  fast_finish: true
