language: ruby
sudo: false
bundler_args: "--without documentation --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}"
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "rm -rf spec/dummy"
  - gem install bundler
before_script:
  - bundle update
  - bundle exec rails dummy:app --trace
  - bundle exec rails app:db:migrate RAILS_ENV=test
cache: bundler
script: bundle exec rspec
env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite
rvm:
  # - 2.2.4
  - 2.3.1
matrix:
  fast_finish: true
