language: ruby
sudo: false
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "rm -rf spec/dummy"
  - gem install bundler
before_script:
  - bundle update
  - bundle exec rails dummy:app --trace
  - bundle exec rails app:db:migrate --trace
  - bundle exec rails app:db:test:prepare --trace
  - bundle exec rails app:db:migrate RAILS_ENV=test
cache: bundler
script: bundle exec rspec
env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite
rvm:
  - 2.2.4
  - 2.3.1
matrix:
  fast_finish: true
