language: ruby
# cache: bundler
# bundler_args: --without development
before_script:
  - bundle exec rake dummy:app --trace
  - bundle exec rake app:db:migrate --trace
script: bundle exec rspec spec
env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite
rvm:
  - 2.1.0
