language: ruby
sudo: false
cache: bundler
# bundler_args: --without development
before_install: gem install bundler
before_script:
  - bundle exec rake dummy:app --trace
  - bundle exec rake app:db:migrate --trace
script: bundle exec rspec spec
env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite
rvm:
  - 2.1.1
  - 2.2.2
matrix:
  fast_finish: true
