language: ruby
dist: trusty
sudo: false
bundler_args: "--without documentation --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}"
before_install:
  - "rm Gemfile.lock"
  - "rm -rf spec/dummy"
  - "gem update --system"
  - "gem install bundler"


before_script:
  - bundle update
  - bundle exec rails dummy:app --trace
  - cp travis/database.yml spec/dummy/config/database.yml
  - mysql -e 'CREATE DATABASE socializer_test;'
  - psql -c 'create database socializer_test;' -U postgres
  - bundle exec rails app:db:migrate RAILS_ENV=test

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

script:
  - "bundle exec rspec"
  - "bundle exec codeclimate-test-reporter"

# env:
#   - DB=postgres
#   - DB=mysql
#   - DB=sqlite

# rvm:
#   # - 2.2.4
#   # - 2.3.3
#   - 2.4.1

# gemfile:
#   - Gemfile
#   - gemfiles/gemfile.pg
#   - gemfiles/gemfile.mysql

matrix:
  fast_finish: true
  include:
    - rvm: 2.4.1
      gemfile: Gemfile
      env: DB=sqlite
    - rvm: 2.4.1
      gemfile: gemfiles/gemfile.pg
      env: DB=postgres
      services: postgresql
    - rvm: 2.4.1
      gemfile: gemfiles/gemfile.mysql
      env: DB=mysql
      services: mysql

addons:
  code_climate:
    repo_token: 08c7e43e5cdaf0614c7e61dcf6279865630cb6992fa9f1f09856f72fd641218b
