# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6575186b5340ebf8fca2edf2642c061e13e593317d05e34564f8284d82ca848d3f36a5122d5e31ba7007bf293eb650443e59642a05ec6fc83f85cd752f04383

test:
  secret_key_base: 4809ef46a9e1b4cc2e0d9b1f5c4625ad105578b171f9054c9b8e7e6eacccc22c25a7dff5345e0a0507a79717afdf19540e72d11d3beee98843bf4f5ecda985cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
